Traceback (most recent call last):
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
NUM_EPOCHS = 10
lr = 1e-2
# Define optimizer and loss function
optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
for epoch in range(NUM_EPOCHS):
    train_loss = train(model, tr_dataloader, optimizer)
    valid_loss = test(model, te_dataloader)
    print("[Epoch %d/%d] [Train Loss: %.4f] [Valid Loss: %.4f]" % (epoch + 1, NUM_EPOCHS, train_loss, valid_loss))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[10], line 6[0m
[1;32m      4[0m optimizer [38;5;241m=[39m torch[38;5;241m.[39moptim[38;5;241m.[39mAdamW(model[38;5;241m.[39mparameters(), lr[38;5;241m=[39mlr)
[1;32m      5[0m [38;5;28;01mfor[39;00m epoch [38;5;129;01min[39;00m [38;5;28mrange[39m(NUM_EPOCHS):
[0;32m----> 6[0m     train_loss [38;5;241m=[39m [43mtrain[49m[43m([49m[43mmodel[49m[43m,[49m[43m [49m[43mtr_dataloader[49m[43m,[49m[43m [49m[43moptimizer[49m[43m)[49m
[1;32m      7[0m     valid_loss [38;5;241m=[39m test(model, te_dataloader)
[1;32m      8[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m[Epoch [39m[38;5;132;01m%d[39;00m[38;5;124m/[39m[38;5;132;01m%d[39;00m[38;5;124m] [Train Loss: [39m[38;5;132;01m%.4f[39;00m[38;5;124m] [Valid Loss: [39m[38;5;132;01m%.4f[39;00m[38;5;124m][39m[38;5;124m"[39m [38;5;241m%[39m (epoch [38;5;241m+[39m [38;5;241m1[39m, NUM_EPOCHS, train_loss, valid_loss))

Cell [0;32mIn[9], line 4[0m, in [0;36mtrain[0;34m(model, dataloader, optimizer)[0m
[1;32m      2[0m model[38;5;241m.[39mtrain()
[1;32m      3[0m total_loss [38;5;241m=[39m [38;5;241m0[39m
[0;32m----> 4[0m pbar [38;5;241m=[39m [43mtqdm[49m[43m([49m[43mdataloader[49m[43m,[49m[43m [49m[43mdesc[49m[38;5;241;43m=[39;49m[38;5;124;43mf[39;49m[38;5;124;43m'[39;49m[38;5;124;43mTRAIN Epoch [39;49m[38;5;132;43;01m{[39;49;00m[43mepoch[49m[38;5;132;43;01m:[39;49;00m[38;5;124;43m02[39;49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      5[0m [38;5;28;01mfor[39;00m batch [38;5;129;01min[39;00m pbar:
[1;32m      6[0m     optimizer[38;5;241m.[39mzero_grad()

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/tqdm/notebook.py:234[0m, in [0;36mtqdm_notebook.__init__[0;34m(self, *args, **kwargs)[0m
[1;32m    232[0m unit_scale [38;5;241m=[39m [38;5;241m1[39m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39munit_scale [38;5;129;01mis[39;00m [38;5;28;01mTrue[39;00m [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39munit_scale [38;5;129;01mor[39;00m [38;5;241m1[39m
[1;32m    233[0m total [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtotal [38;5;241m*[39m unit_scale [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mtotal [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39mtotal
[0;32m--> 234[0m [38;5;28mself[39m[38;5;241m.[39mcontainer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mstatus_printer[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfp[49m[43m,[49m[43m [49m[43mtotal[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdesc[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mncols[49m[43m)[49m
[1;32m    235[0m [38;5;28mself[39m[38;5;241m.[39mcontainer[38;5;241m.[39mpbar [38;5;241m=[39m proxy([38;5;28mself[39m)
[1;32m    236[0m [38;5;28mself[39m[38;5;241m.[39mdisplayed [38;5;241m=[39m [38;5;28;01mFalse[39;00m

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/tqdm/notebook.py:108[0m, in [0;36mtqdm_notebook.status_printer[0;34m(_, total, desc, ncols)[0m
[1;32m     99[0m [38;5;66;03m# Fallback to text bar if there's no total[39;00m
[1;32m    100[0m [38;5;66;03m# DEPRECATED: replaced with an 'info' style bar[39;00m
[1;32m    101[0m [38;5;66;03m# if not total:[39;00m
[0;32m   (...)[0m
[1;32m    105[0m 
[1;32m    106[0m [38;5;66;03m# Prepare IPython progress bar[39;00m
[1;32m    107[0m [38;5;28;01mif[39;00m IProgress [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:  [38;5;66;03m# #187 #451 #558 #872[39;00m
[0;32m--> 108[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(WARN_NOIPYW)
[1;32m    109[0m [38;5;28;01mif[39;00m total:
[1;32m    110[0m     pbar [38;5;241m=[39m IProgress([38;5;28mmin[39m[38;5;241m=[39m[38;5;241m0[39m, [38;5;28mmax[39m[38;5;241m=[39mtotal)

[0;31mImportError[0m: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

