Traceback (most recent call last):
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import torch
import torchaudio
# import librosa
from einops import rearrange
from stable_audio_tools import get_pretrained_model
from stable_audio_tools.inference.generation import generate_diffusion_cond
import IPython.display as ipd
from functools import partial

device = "cuda" if torch.cuda.is_available() else "cpu"

# Download model
model, model_config = get_pretrained_model("stabilityai/stable-audio-open-1.0")
sample_rate = model_config["sample_rate"]
sample_size = model_config["sample_size"]

model = model.to(device)
------------------

----- stderr -----
/Users/seungheond/anaconda3/envs/p310/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/utils/_http.py:406[0m, in [0;36mhf_raise_for_status[0;34m(response, endpoint_name)[0m
[1;32m    405[0m [38;5;28;01mtry[39;00m:
[0;32m--> 406[0m     [43mresponse[49m[38;5;241;43m.[39;49m[43mraise_for_status[49m[43m([49m[43m)[49m
[1;32m    407[0m [38;5;28;01mexcept[39;00m HTTPError [38;5;28;01mas[39;00m e:

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/requests/models.py:1024[0m, in [0;36mResponse.raise_for_status[0;34m(self)[0m
[1;32m   1023[0m [38;5;28;01mif[39;00m http_error_msg:
[0;32m-> 1024[0m     [38;5;28;01mraise[39;00m HTTPError(http_error_msg, response[38;5;241m=[39m[38;5;28mself[39m)

[0;31mHTTPError[0m: 401 Client Error: Unauthorized for url: https://huggingface.co/stabilityai/stable-audio-open-1.0/resolve/main/model_config.json

The above exception was the direct cause of the following exception:

[0;31mGatedRepoError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 13[0m
[1;32m     10[0m device [38;5;241m=[39m [38;5;124m"[39m[38;5;124mcuda[39m[38;5;124m"[39m [38;5;28;01mif[39;00m torch[38;5;241m.[39mcuda[38;5;241m.[39mis_available() [38;5;28;01melse[39;00m [38;5;124m"[39m[38;5;124mcpu[39m[38;5;124m"[39m
[1;32m     12[0m [38;5;66;03m# Download model[39;00m
[0;32m---> 13[0m model, model_config [38;5;241m=[39m [43mget_pretrained_model[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mstabilityai/stable-audio-open-1.0[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m     14[0m sample_rate [38;5;241m=[39m model_config[[38;5;124m"[39m[38;5;124msample_rate[39m[38;5;124m"[39m]
[1;32m     15[0m sample_size [38;5;241m=[39m model_config[[38;5;124m"[39m[38;5;124msample_size[39m[38;5;124m"[39m]

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/stable_audio_tools/models/pretrained.py:10[0m, in [0;36mget_pretrained_model[0;34m(name)[0m
[1;32m      8[0m [38;5;28;01mdef[39;00m [38;5;21mget_pretrained_model[39m(name: [38;5;28mstr[39m):
[0;32m---> 10[0m     model_config_path [38;5;241m=[39m [43mhf_hub_download[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mfilename[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mmodel_config.json[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mrepo_type[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mmodel[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m     12[0m     [38;5;28;01mwith[39;00m [38;5;28mopen[39m(model_config_path) [38;5;28;01mas[39;00m f:
[1;32m     13[0m         model_config [38;5;241m=[39m json[38;5;241m.[39mload(f)

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py:114[0m, in [0;36mvalidate_hf_hub_args.<locals>._inner_fn[0;34m(*args, **kwargs)[0m
[1;32m    111[0m [38;5;28;01mif[39;00m check_use_auth_token:
[1;32m    112[0m     kwargs [38;5;241m=[39m smoothly_deprecate_use_auth_token(fn_name[38;5;241m=[39mfn[38;5;241m.[39m[38;5;18m__name__[39m, has_token[38;5;241m=[39mhas_token, kwargs[38;5;241m=[39mkwargs)
[0;32m--> 114[0m [38;5;28;01mreturn[39;00m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/file_download.py:862[0m, in [0;36mhf_hub_download[0;34m(repo_id, filename, subfolder, repo_type, revision, library_name, library_version, cache_dir, local_dir, user_agent, force_download, proxies, etag_timeout, token, local_files_only, headers, endpoint, resume_download, force_filename, local_dir_use_symlinks)[0m
[1;32m    842[0m     [38;5;28;01mreturn[39;00m _hf_hub_download_to_local_dir(
[1;32m    843[0m         [38;5;66;03m# Destination[39;00m
[1;32m    844[0m         local_dir[38;5;241m=[39mlocal_dir,
[0;32m   (...)[0m
[1;32m    859[0m         local_files_only[38;5;241m=[39mlocal_files_only,
[1;32m    860[0m     )
[1;32m    861[0m [38;5;28;01melse[39;00m:
[0;32m--> 862[0m     [38;5;28;01mreturn[39;00m [43m_hf_hub_download_to_cache_dir[49m[43m([49m
[1;32m    863[0m [43m        [49m[38;5;66;43;03m# Destination[39;49;00m
[1;32m    864[0m [43m        [49m[43mcache_dir[49m[38;5;241;43m=[39;49m[43mcache_dir[49m[43m,[49m
[1;32m    865[0m [43m        [49m[38;5;66;43;03m# File info[39;49;00m
[1;32m    866[0m [43m        [49m[43mrepo_id[49m[38;5;241;43m=[39;49m[43mrepo_id[49m[43m,[49m
[1;32m    867[0m [43m        [49m[43mfilename[49m[38;5;241;43m=[39;49m[43mfilename[49m[43m,[49m
[1;32m    868[0m [43m        [49m[43mrepo_type[49m[38;5;241;43m=[39;49m[43mrepo_type[49m[43m,[49m
[1;32m    869[0m [43m        [49m[43mrevision[49m[38;5;241;43m=[39;49m[43mrevision[49m[43m,[49m
[1;32m    870[0m [43m        [49m[38;5;66;43;03m# HTTP info[39;49;00m
[1;32m    871[0m [43m        [49m[43mendpoint[49m[38;5;241;43m=[39;49m[43mendpoint[49m[43m,[49m
[1;32m    872[0m [43m        [49m[43metag_timeout[49m[38;5;241;43m=[39;49m[43metag_timeout[49m[43m,[49m
[1;32m    873[0m [43m        [49m[43mheaders[49m[38;5;241;43m=[39;49m[43mheaders[49m[43m,[49m
[1;32m    874[0m [43m        [49m[43mproxies[49m[38;5;241;43m=[39;49m[43mproxies[49m[43m,[49m
[1;32m    875[0m [43m        [49m[43mtoken[49m[38;5;241;43m=[39;49m[43mtoken[49m[43m,[49m
[1;32m    876[0m [43m        [49m[38;5;66;43;03m# Additional options[39;49;00m
[1;32m    877[0m [43m        [49m[43mlocal_files_only[49m[38;5;241;43m=[39;49m[43mlocal_files_only[49m[43m,[49m
[1;32m    878[0m [43m        [49m[43mforce_download[49m[38;5;241;43m=[39;49m[43mforce_download[49m[43m,[49m
[1;32m    879[0m [43m    [49m[43m)[49m

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/file_download.py:969[0m, in [0;36m_hf_hub_download_to_cache_dir[0;34m(cache_dir, repo_id, filename, repo_type, revision, endpoint, etag_timeout, headers, proxies, token, local_files_only, force_download)[0m
[1;32m    966[0m                 [38;5;28;01mreturn[39;00m pointer_path
[1;32m    968[0m     [38;5;66;03m# Otherwise, raise appropriate error[39;00m
[0;32m--> 969[0m     [43m_raise_on_head_call_error[49m[43m([49m[43mhead_call_error[49m[43m,[49m[43m [49m[43mforce_download[49m[43m,[49m[43m [49m[43mlocal_files_only[49m[43m)[49m
[1;32m    971[0m [38;5;66;03m# From now on, etag, commit_hash, url and size are not None.[39;00m
[1;32m    972[0m [38;5;28;01massert[39;00m etag [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m, [38;5;124m"[39m[38;5;124metag must have been retrieved from server[39m[38;5;124m"[39m

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/file_download.py:1484[0m, in [0;36m_raise_on_head_call_error[0;34m(head_call_error, force_download, local_files_only)[0m
[1;32m   1478[0m     [38;5;28;01mraise[39;00m LocalEntryNotFoundError(
[1;32m   1479[0m         [38;5;124m"[39m[38;5;124mCannot find the requested files in the disk cache and outgoing traffic has been disabled. To enable[39m[38;5;124m"[39m
[1;32m   1480[0m         [38;5;124m"[39m[38;5;124m hf.co look-ups and downloads online, set [39m[38;5;124m'[39m[38;5;124mlocal_files_only[39m[38;5;124m'[39m[38;5;124m to False.[39m[38;5;124m"[39m
[1;32m   1481[0m     )
[1;32m   1482[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(head_call_error, RepositoryNotFoundError) [38;5;129;01mor[39;00m [38;5;28misinstance[39m(head_call_error, GatedRepoError):
[1;32m   1483[0m     [38;5;66;03m# Repo not found or gated => let's raise the actual error[39;00m
[0;32m-> 1484[0m     [38;5;28;01mraise[39;00m head_call_error
[1;32m   1485[0m [38;5;28;01melse[39;00m:
[1;32m   1486[0m     [38;5;66;03m# Otherwise: most likely a connection issue or Hub downtime => let's warn the user[39;00m
[1;32m   1487[0m     [38;5;28;01mraise[39;00m LocalEntryNotFoundError(
[1;32m   1488[0m         [38;5;124m"[39m[38;5;124mAn error happened while trying to locate the file on the Hub and we cannot find the requested files[39m[38;5;124m"[39m
[1;32m   1489[0m         [38;5;124m"[39m[38;5;124m in the local cache. Please check your connection and try again or make sure your Internet connection[39m[38;5;124m"[39m
[1;32m   1490[0m         [38;5;124m"[39m[38;5;124m is on.[39m[38;5;124m"[39m
[1;32m   1491[0m     ) [38;5;28;01mfrom[39;00m [38;5;21;01mhead_call_error[39;00m

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/file_download.py:1376[0m, in [0;36m_get_metadata_or_catch_error[0;34m(repo_id, filename, repo_type, revision, endpoint, proxies, etag_timeout, headers, token, local_files_only, relative_filename, storage_folder)[0m
[1;32m   1374[0m [38;5;28;01mtry[39;00m:
[1;32m   1375[0m     [38;5;28;01mtry[39;00m:
[0;32m-> 1376[0m         metadata [38;5;241m=[39m [43mget_hf_file_metadata[49m[43m([49m
[1;32m   1377[0m [43m            [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m[43m [49m[43mproxies[49m[38;5;241;43m=[39;49m[43mproxies[49m[43m,[49m[43m [49m[43mtimeout[49m[38;5;241;43m=[39;49m[43metag_timeout[49m[43m,[49m[43m [49m[43mheaders[49m[38;5;241;43m=[39;49m[43mheaders[49m[43m,[49m[43m [49m[43mtoken[49m[38;5;241;43m=[39;49m[43mtoken[49m
[1;32m   1378[0m [43m        [49m[43m)[49m
[1;32m   1379[0m     [38;5;28;01mexcept[39;00m EntryNotFoundError [38;5;28;01mas[39;00m http_error:
[1;32m   1380[0m         [38;5;28;01mif[39;00m storage_folder [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m relative_filename [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1381[0m             [38;5;66;03m# Cache the non-existence of the file[39;00m

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py:114[0m, in [0;36mvalidate_hf_hub_args.<locals>._inner_fn[0;34m(*args, **kwargs)[0m
[1;32m    111[0m [38;5;28;01mif[39;00m check_use_auth_token:
[1;32m    112[0m     kwargs [38;5;241m=[39m smoothly_deprecate_use_auth_token(fn_name[38;5;241m=[39mfn[38;5;241m.[39m[38;5;18m__name__[39m, has_token[38;5;241m=[39mhas_token, kwargs[38;5;241m=[39mkwargs)
[0;32m--> 114[0m [38;5;28;01mreturn[39;00m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/file_download.py:1296[0m, in [0;36mget_hf_file_metadata[0;34m(url, token, proxies, timeout, library_name, library_version, user_agent, headers)[0m
[1;32m   1293[0m headers[[38;5;124m"[39m[38;5;124mAccept-Encoding[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;124m"[39m[38;5;124midentity[39m[38;5;124m"[39m  [38;5;66;03m# prevent any compression => we want to know the real size of the file[39;00m
[1;32m   1295[0m [38;5;66;03m# Retrieve metadata[39;00m
[0;32m-> 1296[0m r [38;5;241m=[39m [43m_request_wrapper[49m[43m([49m
[1;32m   1297[0m [43m    [49m[43mmethod[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mHEAD[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m   1298[0m [43m    [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m
[1;32m   1299[0m [43m    [49m[43mheaders[49m[38;5;241;43m=[39;49m[43mheaders[49m[43m,[49m
[1;32m   1300[0m [43m    [49m[43mallow_redirects[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[1;32m   1301[0m [43m    [49m[43mfollow_relative_redirects[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m
[1;32m   1302[0m [43m    [49m[43mproxies[49m[38;5;241;43m=[39;49m[43mproxies[49m[43m,[49m
[1;32m   1303[0m [43m    [49m[43mtimeout[49m[38;5;241;43m=[39;49m[43mtimeout[49m[43m,[49m
[1;32m   1304[0m [43m[49m[43m)[49m
[1;32m   1305[0m hf_raise_for_status(r)
[1;32m   1307[0m [38;5;66;03m# Return[39;00m

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/file_download.py:277[0m, in [0;36m_request_wrapper[0;34m(method, url, follow_relative_redirects, **params)[0m
[1;32m    275[0m [38;5;66;03m# Recursively follow relative redirects[39;00m
[1;32m    276[0m [38;5;28;01mif[39;00m follow_relative_redirects:
[0;32m--> 277[0m     response [38;5;241m=[39m [43m_request_wrapper[49m[43m([49m
[1;32m    278[0m [43m        [49m[43mmethod[49m[38;5;241;43m=[39;49m[43mmethod[49m[43m,[49m
[1;32m    279[0m [43m        [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m
[1;32m    280[0m [43m        [49m[43mfollow_relative_redirects[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m
[1;32m    281[0m [43m        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mparams[49m[43m,[49m
[1;32m    282[0m [43m    [49m[43m)[49m
[1;32m    284[0m     [38;5;66;03m# If redirection, we redirect only relative paths.[39;00m
[1;32m    285[0m     [38;5;66;03m# This is useful in case of a renamed repository.[39;00m
[1;32m    286[0m     [38;5;28;01mif[39;00m [38;5;241m300[39m [38;5;241m<[39m[38;5;241m=[39m response[38;5;241m.[39mstatus_code [38;5;241m<[39m[38;5;241m=[39m [38;5;241m399[39m:

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/file_download.py:301[0m, in [0;36m_request_wrapper[0;34m(method, url, follow_relative_redirects, **params)[0m
[1;32m    299[0m [38;5;66;03m# Perform request and return if status_code is not in the retry list.[39;00m
[1;32m    300[0m response [38;5;241m=[39m get_session()[38;5;241m.[39mrequest(method[38;5;241m=[39mmethod, url[38;5;241m=[39murl, [38;5;241m*[39m[38;5;241m*[39mparams)
[0;32m--> 301[0m [43mhf_raise_for_status[49m[43m([49m[43mresponse[49m[43m)[49m
[1;32m    302[0m [38;5;28;01mreturn[39;00m response

File [0;32m~/anaconda3/envs/p310/lib/python3.10/site-packages/huggingface_hub/utils/_http.py:423[0m, in [0;36mhf_raise_for_status[0;34m(response, endpoint_name)[0m
[1;32m    419[0m [38;5;28;01melif[39;00m error_code [38;5;241m==[39m [38;5;124m"[39m[38;5;124mGatedRepo[39m[38;5;124m"[39m:
[1;32m    420[0m     message [38;5;241m=[39m (
[1;32m    421[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mresponse[38;5;241m.[39mstatus_code[38;5;132;01m}[39;00m[38;5;124m Client Error.[39m[38;5;124m"[39m [38;5;241m+[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m [38;5;241m+[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124mCannot access gated repo for url [39m[38;5;132;01m{[39;00mresponse[38;5;241m.[39murl[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m"[39m
[1;32m    422[0m     )
[0;32m--> 423[0m     [38;5;28;01mraise[39;00m _format(GatedRepoError, message, response) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m    425[0m [38;5;28;01melif[39;00m error_message [38;5;241m==[39m [38;5;124m"[39m[38;5;124mAccess to this resource is disabled.[39m[38;5;124m"[39m:
[1;32m    426[0m     message [38;5;241m=[39m (
[1;32m    427[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mresponse[38;5;241m.[39mstatus_code[38;5;132;01m}[39;00m[38;5;124m Client Error.[39m[38;5;124m"[39m
[1;32m    428[0m         [38;5;241m+[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[0;32m   (...)[0m
[1;32m    431[0m         [38;5;241m+[39m [38;5;124m"[39m[38;5;124mAccess to this resource is disabled.[39m[38;5;124m"[39m
[1;32m    432[0m     )

[0;31mGatedRepoError[0m: 401 Client Error. (Request ID: Root=1-6730f40e-0035d0002276c8da3c048b22;8b4d2fe6-7b98-4702-a05b-cd7565572fb1)

Cannot access gated repo for url https://huggingface.co/stabilityai/stable-audio-open-1.0/resolve/main/model_config.json.
Access to model stabilityai/stable-audio-open-1.0 is restricted. You must have access to it and be authenticated to access it. Please log in.

